// Copyright 2026 Canonical.

package jujuapi

import (
	"os"
	"path/filepath"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/canonical/jimm/v3/internal/jujuapi/legacywire"
)

// TestLegacyWireShapesGolden pins the field/json-tag signatures of the 3.6 wire
// structs, so a juju bump that silently renames a field (e.g. owner-tag ->
// qualifier) or drops a *Legacy struct fails CI loudly. This is the one drift
// class facade-version negotiation cannot catch.
//
// The golden file is generated by cmd/legacywire (not by this test); regenerate
// an intentional change with `make update-golden`. The advertised facade/version
// matrix is guarded separately by the generated facadeversions.go and CI's
// verify_generated job.
func TestLegacyWireShapesGolden(t *testing.T) {
	c := qt.New(t)

	path := filepath.Join("testdata", "legacy_wire_shapes.json")
	want, err := os.ReadFile(path)
	c.Assert(err, qt.IsNil, qt.Commentf("missing golden file %s; regenerate with `make update-golden`", path))

	c.Assert(string(legacywire.Golden()), qt.Equals, string(want), qt.Commentf(
		"golden mismatch for %s.\n"+
			"The 3.6 wire shapes changed; this may be a juju bump silently "+
			"altering a *Legacy struct.\n"+
			"If intentional, regenerate with `make update-golden`.", path))
}

// TestAdvertisedVersionsAreDispatchable asserts that every facade version
// advertised at login has at least one registered method, so a forgotten
// back-ported version fails here rather than as a runtime CallNotImplemented.
func TestAdvertisedVersionsAreDispatchable(t *testing.T) {
	c := qt.New(t)

	root := newControllerRoot(nil, Params{}, "")
	facades := setupFacades(root)
	c.Assert(len(facades) > 0, qt.IsTrue)
	for _, fv := range facades {
		c.Assert(len(fv.Versions) > 0, qt.IsTrue, qt.Commentf("facade %q advertises no versions", fv.Name))
		for _, v := range fv.Versions {
			c.Check(root.HasMethods(fv.Name, v), qt.IsTrue,
				qt.Commentf("facade %q advertises version %d but registers no methods for it", fv.Name, v))
		}
	}
}
