// Copyright 2026 Canonical.

// Package legacywire owns the list of Juju 3.6 ("legacy") wire structs JIMM
// serves to, or accepts from, 3.6 clients, and renders a deterministic golden
// snapshot of their field/json-tag signatures.
//
// The snapshot is the one drift class that facade-version negotiation cannot
// catch: a juju dependency bump that silently renames a field (e.g.
// owner-tag -> qualifier) or drops a *Legacy struct at a fixed facade version.
// It is generated by cmd/legacywire into a committed file and guarded in CI
// (see internal/jujuapi/generate.go and the verify_generated job).
//
// The package is deliberately importable by both the generator binary and the
// jujuapi test: it imports only juju's params package, never internal/jujuapi,
// so the test (package jujuapi) can compare against Golden() without an import
// cycle.
package legacywire

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	jujuparams "github.com/juju/juju/rpc/params"
)

// header is prepended to the golden file. It is part of the rendered bytes, so
// the comparison test and the generator agree on it byte-for-byte.
const header = `# Code generated by cmd/legacywire; DO NOT EDIT.
#
# Field/json-tag signatures of the Juju 3.6 wire structs JIMM serves. A renamed,
# retyped, added or removed field (most importantly a silent owner-tag ->
# qualifier rename on a juju bump) changes this file and fails CI.
#
# Regenerate with: make update-golden

`

// Types are the structs JIMM serves to (or accepts from) Juju 3.6 clients whose
// shape juju controls and could change at a fixed facade version. They are
// mostly the juju "*Legacy" twins; ModelConfigResults is included because
// ModelConfig v3 reuses it unchanged.
func Types() []any {
	return []any{
		jujuparams.ModelCreateArgsLegacy{},
		jujuparams.ModelInfoLegacy{},
		jujuparams.ModelInfoResultLegacy{},
		jujuparams.ModelInfoResultsLegacy{},
		jujuparams.ModelLegacy{},
		jujuparams.UserModelLegacy{},
		jujuparams.UserModelListLegacy{},
		jujuparams.ModelStatusLegacy{},
		jujuparams.ModelStatusResultsLegacy{},
		jujuparams.ModelSummaryLegacy{},
		jujuparams.ModelSummaryResultLegacy{},
		jujuparams.ModelSummaryResultsLegacy{},
		jujuparams.OfferFilterLegacy{},
		jujuparams.OfferFiltersLegacy{},
		jujuparams.ModelConfigResults{},
	}
}

// Golden renders the deterministic golden snapshot of Types(). The output is
// stable across runs (types and fields are sorted by name), so it can be
// committed and diffed.
func Golden() []byte {
	type sig struct {
		name, body string
	}
	types := Types()
	sigs := make([]sig, 0, len(types))
	for _, v := range types {
		rt := reflect.TypeOf(v)
		sigs = append(sigs, sig{name: rt.Name(), body: structSignature(rt)})
	}
	sort.Slice(sigs, func(i, j int) bool { return sigs[i].name < sigs[j].name })

	var b strings.Builder
	b.WriteString(header)
	for _, s := range sigs {
		fmt.Fprintf(&b, "=== %s ===\n%s\n\n", s.name, s.body)
	}
	return []byte(b.String())
}

// structSignature returns a deterministic, one-level description of a struct's
// fields: name, json tag and type. A renamed/retyped/added/removed field
// changes the signature.
func structSignature(t reflect.Type) string {
	fields := make([]string, 0, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		fields = append(fields, fmt.Sprintf("%s `json:%q` %s", f.Name, f.Tag.Get("json"), f.Type.String()))
	}
	sort.Strings(fields)
	return strings.Join(fields, "\n")
}
