// Copyright 2026 Canonical.

// Package legacywire owns the list of Juju 3.6 ("legacy") wire structs JIMM
// serves to, or accepts from, 3.6 clients, and renders a deterministic golden
// snapshot of their field/json-tag signatures.
//
// The snapshot is the one drift class that facade-version negotiation cannot
// catch: a juju dependency bump that silently renames a field (e.g.
// owner-tag -> qualifier) or drops a *Legacy struct at a fixed facade version.
// It is generated by cmd/legacywire into a committed file and guarded in CI
// (see internal/jujuapi/generate.go and the verify_generated job).
//
// The package is deliberately importable by both the generator binary and the
// jujuapi test: it imports only juju's params package, never internal/jujuapi,
// so the test (package jujuapi) can compare against Golden() without an import
// cycle.
package legacywire

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"

	jujuparams "github.com/juju/juju/rpc/params"
)

// header is prepended to the golden file. It is part of the rendered bytes, so
// the comparison test and the generator agree on it byte-for-byte.
const header = `# Code generated by cmd/legacywire; DO NOT EDIT.
#
# Field/json-tag signatures of the Juju 3.6 wire structs JIMM serves, plus
# every juju-owned struct reachable from them (the nested types that form the
# rest of the wire tree). A renamed, retyped, added or removed field anywhere
# in the tree (most importantly a silent owner-tag -> qualifier rename on a
# juju bump) changes this file and fails CI. Types with custom JSON marshaling
# are pinned by name only: their fields do not describe their wire shape.
#
# Regenerate with: make update-golden

`

// Types are the structs JIMM serves to (or accepts from) Juju 3.6 clients whose
// shape juju controls and could change at a fixed facade version. They are
// mostly the juju "*Legacy" twins; ModelConfigResults is included because
// ModelConfig v3 reuses it unchanged. The snapshot also covers every juju-owned
// struct reachable from these roots, so only the roots need listing here.
func Types() []any {
	return []any{
		jujuparams.ModelCreateArgsLegacy{},
		jujuparams.ModelInfoLegacy{},
		jujuparams.ModelInfoResultLegacy{},
		jujuparams.ModelInfoResultsLegacy{},
		jujuparams.ModelLegacy{},
		jujuparams.UserModelLegacy{},
		jujuparams.UserModelListLegacy{},
		jujuparams.ModelStatusLegacy{},
		jujuparams.ModelStatusResultsLegacy{},
		jujuparams.ModelSummaryLegacy{},
		jujuparams.ModelSummaryResultLegacy{},
		jujuparams.ModelSummaryResultsLegacy{},
		jujuparams.OfferFilterLegacy{},
		jujuparams.OfferFiltersLegacy{},
		jujuparams.ModelConfigResults{},
		// ModelUpgrader v1 wire types. These have no *Legacy twin: juju serves
		// them unchanged to 3.6 and 4.x clients at a fixed facade version,
		// which is exactly the no-version-signal drift class this guard
		// exists for.
		jujuparams.ModelParam{},
		jujuparams.UpgradeModelParams{},
		jujuparams.UpgradeModelResult{},
	}
}

// Golden renders the deterministic golden snapshot: one section per juju-owned
// named struct type reachable from Types() — the roots plus every nested
// struct that forms part of the wire format. The output is stable across runs
// (types and fields are sorted by name), so it can be committed and diffed.
func Golden() []byte {
	seen := make(map[reflect.Type]bool)
	for _, v := range Types() {
		collect(reflect.TypeOf(v), seen)
	}

	type sig struct {
		name, body string
	}
	sigs := make([]sig, 0, len(seen))
	for t := range seen {
		body := structSignature(t)
		if hasCustomJSON(t) {
			body = "(custom JSON marshaling; wire shape is not field-based)"
		}
		sigs = append(sigs, sig{name: t.String(), body: body})
	}
	sort.Slice(sigs, func(i, j int) bool { return sigs[i].name < sigs[j].name })

	var b strings.Builder
	b.WriteString(header)
	for _, s := range sigs {
		fmt.Fprintf(&b, "=== %s ===\n%s\n\n", s.name, s.body)
	}
	return []byte(b.String())
}

// collect adds to seen every juju-owned named struct type reachable from t
// through pointers, slices, arrays, maps and struct fields. Types outside
// juju's module tree (std lib, JIMM's own) are leaves: juju cannot drift them
// under us. Types with custom JSON marshaling are recorded but not descended
// into, since their fields do not describe their wire shape.
func collect(t reflect.Type, seen map[reflect.Type]bool) {
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array:
		collect(t.Elem(), seen)
	case reflect.Map:
		collect(t.Key(), seen)
		collect(t.Elem(), seen)
	case reflect.Struct:
		if seen[t] || !strings.HasPrefix(t.PkgPath(), "github.com/juju/") {
			return
		}
		seen[t] = true
		if hasCustomJSON(t) {
			return
		}
		for i := 0; i < t.NumField(); i++ {
			collect(t.Field(i).Type, seen)
		}
	}
}

var jsonMarshalerType = reflect.TypeOf((*json.Marshaler)(nil)).Elem()

// hasCustomJSON reports whether t (or *t, whose method set encoding/json also
// honours for addressable values) marshals itself, in which case its fields
// are not its wire shape.
func hasCustomJSON(t reflect.Type) bool {
	return reflect.PointerTo(t).Implements(jsonMarshalerType)
}

// structSignature returns a deterministic, one-level description of a struct's
// fields: name, json tag and type. A renamed/retyped/added/removed field
// changes the signature.
func structSignature(t reflect.Type) string {
	fields := make([]string, 0, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		fields = append(fields, fmt.Sprintf("%s `json:%q` %s", f.Name, f.Tag.Get("json"), f.Type.String()))
	}
	sort.Strings(fields)
	return strings.Join(fields, "\n")
}
