// Copyright 2026 Canonical.

// Package legacywire owns the list of Juju 3.6 ("legacy") wire structs JIMM
// serves to, or accepts from, 3.6 clients, and renders a deterministic golden
// snapshot of their field/json-tag signatures.
//
// The snapshot is the one drift class that facade-version negotiation cannot
// catch: a juju dependency bump that silently renames a field (e.g.
// owner-tag -> qualifier) or drops a *Legacy struct at a fixed facade version.
// It is generated by cmd/legacywire into a committed file and guarded in CI
// (see internal/jujuapi/generate.go and the verify_generated job).
//
// The package is deliberately importable by both the generator binary and the
// jujuapi test: it imports only juju's params package, never internal/jujuapi,
// so the test (package jujuapi) can compare against Golden() without an import
// cycle.
package legacywire

import (
	"bytes"
	"encoding/json"
	"reflect"
	"strings"

	jujuparams "github.com/juju/juju/rpc/params"
)

// comment is rendered into the golden document's "$comment" field: JSON has no
// comments, so the file's provenance and purpose travel inside the document.
var comment = []string{
	"Code generated by cmd/legacywire; DO NOT EDIT.",
	"Field/json-tag signatures of the Juju 3.6 wire structs JIMM serves, plus",
	"every juju-owned struct reachable from them (the nested types that form the",
	"rest of the wire tree). A renamed, retyped, added or removed field anywhere",
	"in the tree (most importantly a silent owner-tag -> qualifier rename on a",
	"juju bump) changes this file and fails CI. Types with custom JSON marshaling",
	"are pinned by name only: their fields do not describe their wire shape.",
	"Regenerate with: make update-golden",
}

// document is the top-level shape of the golden file.
type document struct {
	Comment []string             `json:"$comment"`
	Types   map[string]signature `json:"types"`
}

// signature is one type's entry in the golden document. Exactly one of Fields
// or CustomJSONMarshaler is set.
type signature struct {
	// CustomJSONMarshaler marks a type that marshals itself: its Go fields do
	// not describe its wire shape, so it is pinned by name only.
	CustomJSONMarshaler bool `json:"custom-json-marshaler,omitempty"`
	// Fields maps each Go field name to its json tag and Go type.
	Fields map[string]field `json:"fields,omitempty"`
}

// field pins one struct field's wire name and Go type.
type field struct {
	JSONTag string `json:"json"`
	Type    string `json:"type"`
}

// Types are the structs JIMM serves to (or accepts from) Juju 3.6 clients whose
// shape juju controls and could change at a fixed facade version. They are
// mostly the juju "*Legacy" twins; ModelConfigResults is included because
// ModelConfig v3 reuses it unchanged. The snapshot also covers every juju-owned
// struct reachable from these roots, so only the roots need listing here.
func Types() []any {
	return []any{
		jujuparams.ModelCreateArgsLegacy{},
		jujuparams.ModelInfoLegacy{},
		jujuparams.ModelInfoResultLegacy{},
		jujuparams.ModelInfoResultsLegacy{},
		jujuparams.ModelLegacy{},
		jujuparams.UserModelLegacy{},
		jujuparams.UserModelListLegacy{},
		jujuparams.ModelStatusLegacy{},
		jujuparams.ModelStatusResultsLegacy{},
		jujuparams.ModelSummaryLegacy{},
		jujuparams.ModelSummaryResultLegacy{},
		jujuparams.ModelSummaryResultsLegacy{},
		jujuparams.OfferFilterLegacy{},
		jujuparams.OfferFiltersLegacy{},
		jujuparams.ModelConfigResults{},
		// ModelUpgrader v1 wire types. These have no *Legacy twin: juju serves
		// them unchanged to 3.6 and 4.x clients at a fixed facade version,
		// which is exactly the no-version-signal drift class this guard
		// exists for.
		jujuparams.ModelParam{},
		jujuparams.UpgradeModelParams{},
		jujuparams.UpgradeModelResult{},
	}
}

// Golden renders the deterministic golden snapshot as indented JSON: one entry
// per juju-owned named struct type reachable from Types() — the roots plus
// every nested struct that forms part of the wire format. encoding/json sorts
// map keys, so the output is stable across runs and can be committed and
// diffed.
func Golden() []byte {
	seen := make(map[reflect.Type]bool)
	for _, v := range Types() {
		collect(reflect.TypeOf(v), seen)
	}

	types := make(map[string]signature, len(seen))
	for t := range seen {
		types[t.String()] = typeSignature(t)
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(document{Comment: comment, Types: types}); err != nil {
		// The document is plain strings and bools; Encode cannot fail.
		panic(err)
	}
	return buf.Bytes()
}

// collect adds to seen every juju-owned named struct type reachable from t
// through pointers, slices, arrays, maps and struct fields. Types outside
// juju's module tree (std lib, JIMM's own) are leaves: juju cannot drift them
// under us. Types with custom JSON marshaling are recorded but not descended
// into, since their fields do not describe their wire shape.
func collect(t reflect.Type, seen map[reflect.Type]bool) {
	switch t.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Array:
		collect(t.Elem(), seen)
	case reflect.Map:
		collect(t.Key(), seen)
		collect(t.Elem(), seen)
	case reflect.Struct:
		if seen[t] || !strings.HasPrefix(t.PkgPath(), "github.com/juju/") {
			return
		}
		seen[t] = true
		if hasCustomJSON(t) {
			return
		}
		for i := 0; i < t.NumField(); i++ {
			collect(t.Field(i).Type, seen)
		}
	}
}

var jsonMarshalerType = reflect.TypeOf((*json.Marshaler)(nil)).Elem()

// hasCustomJSON reports whether t (or *t, whose method set encoding/json also
// honours for addressable values) marshals itself, in which case its fields
// are not its wire shape.
func hasCustomJSON(t reflect.Type) bool {
	return reflect.PointerTo(t).Implements(jsonMarshalerType)
}

// typeSignature returns t's golden entry: its field/json-tag map, or a
// custom-marshaler marker when the fields do not describe the wire shape. A
// renamed/retyped/added/removed field changes the signature.
func typeSignature(t reflect.Type) signature {
	if hasCustomJSON(t) {
		return signature{CustomJSONMarshaler: true}
	}
	fields := make(map[string]field, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		fields[f.Name] = field{JSONTag: f.Tag.Get("json"), Type: f.Type.String()}
	}
	return signature{Fields: fields}
}
